### ISSUE TITLE
Can't locate Meteor/Syslog.pm in @INC

### ISSUE THREAD

**Issue by Quix0r** [visitsb/meteorserver#9]
I get this when I try to start meteord the usual way:
````
user@host:~/git/meteorserver/src$ ./meteord -d
Can't locate Meteor/Syslog.pm in @INC (you may need to install the Meteor::Syslog module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./meteord line 49.
BEGIN failed--compilation aborted at ./meteord line 49.
user@host:~/git/meteorserver/src$ 
````

**Comment by mariocloud** [comment]
Hey @Quix0r. Could you solve this problem?

**Comment by Quix0r** [comment]
No, still there and no update (newer commit) was found.

**Comment by visitsb** [comment]
First of all, sorry for late response. Yes I've reproduced this error. Looking at it now & hopefully will have a fix or suggestion to this issue.

**Comment by visitsb** [comment]
@Quix0r - I think `cpan` installs `Sys::Syslog` correctly. Use below command to install the syslog module, then it should work. (More information about [cpan](http://www.cpan.org/modules/INSTALL.html)). Let me know if this solves your issue.

```
cpan Sys::Syslog
```

**Note:** The rpm based install (yum, apt-get) says that `perl-Sys-Syslog` is already installed, but you still get the `Can't locate Meteor/Syslog.pm in @INC` error.

**Comment by Quix0r** [comment]
I have found here a package `libsys-syslog-perl` with `0.29-1+deb7u1` as latest version. It depends on an outdated version of perl: perlapi-5.14.2 which breaks other packages. Yes, messy Debian dependencies. ;-) Using `cpan` is one option but that will install files not being controlled by any package and mixes might mix it.

Or is there a way of sand-boxing `Sys:Syslog`?

**Comment by visitsb** [comment]
Sandboxing perl dependencies might not be straightforward or even worth the try. If your `meteor` server can sit standalone exposed over a TCP Port that will be ideal. 

I usually work with a containerization alternative such as [Docker](https://hub.docker.com/search?q=perl&type=image) (see an example for perl [here](https://www.ecliptik.com/Containerizing-a-Perl-Script/)) since my infrastructure components are only talking over a port & TCP.

An OS level containerization - e.g. [chroot](https://googleweblight.com/?lite_url=https://www.geeksforgeeks.org/linux-virtualization-using-chroot-jail/&f=1) - could be another alternative - you'll have to decide which one suits your needs at this time.
